version : "3.3"
services :
  web :
     image : muhammadnaeem42/node-app:latest
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
